"""ETF轮动策略回测系统 - 主入口。

Usage:
    # Mock数据快速回测
    python main.py --mock

    # 真实数据回测（AKShare + 缓存）
    python main.py

    # Tushare Pro数据源回测（推荐）
    python main.py --source tushare --tushare-token YOUR_TOKEN

    # 自定义日期范围
    python main.py --start 2023-01-01 --end 2024-12-31

    # 自定义初始资金
    python main.py --capital 1000000
"""

from __future__ import annotations

import sys
import io
import argparse

# Windows GBK console fix
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

from config.strategy_config import BACKTEST_CONFIG, SIGNAL_CONFIG, RISK_CONFIG
from backtest.backtest_engine import BacktestEngine


def parse_args():
    parser = argparse.ArgumentParser(description="ETF Rotation Strategy Backtest")
    parser.add_argument("--mock", action="store_true", help="Use mock data")
    parser.add_argument("--source", type=str, default=None,
                        choices=["akshare", "tushare"],
                        help="Data source (akshare or tushare)")
    parser.add_argument("--tushare-token", type=str, default=None,
                        help="Tushare Pro API token")
    parser.add_argument("--start", type=str, default=None, help="Start date (YYYY-MM-DD)")
    parser.add_argument("--end", type=str, default=None, help="End date (YYYY-MM-DD)")
    parser.add_argument("--capital", type=float, default=None, help="Initial capital")
    parser.add_argument("--no-progress", action="store_true", help="Disable progress output")
    return parser.parse_args()


def main():
    args = parse_args()

    # 构建配置
    config = BACKTEST_CONFIG.copy()
    if args.start:
        config["start_date"] = args.start
    if args.end:
        config["end_date"] = args.end
    if args.capital:
        config["initial_capital"] = args.capital

    # 创建引擎并运行
    engine = BacktestEngine(
        config=config,
        signal_config=SIGNAL_CONFIG,
        risk_config=RISK_CONFIG,
        use_mock=args.mock,
        data_source=args.source,
        tushare_token=args.tushare_token,
    )

    result = engine.run(progress=not args.no_progress)

    # CSV exports (reports + charts already generated by engine)
    if not result["trades_df"].empty:
        result["trades_df"].to_csv("output/trades.csv", index=False, encoding="utf-8-sig")

    if not result["nav_series"].empty:
        result["nav_series"].to_csv("output/nav.csv", header=True, encoding="utf-8-sig")

    if not result["signals_df"].empty:
        result["signals_df"].to_csv("output/signals.csv", index=False, encoding="utf-8-sig")

    print("\n  All outputs saved to output/ directory")
    if "report_outputs" in result and "html_report" in result["report_outputs"]:
        print(f"  Open HTML report: {result['report_outputs']['html_report']}")

    return result


if __name__ == "__main__":
    import os
    os.makedirs("output", exist_ok=True)
    main()
